src/cloud_storageapp/urls.py
from django.urls import path
from . import views


app_name = 'cloud_storageapp'

urlpatterns = [
    path('authorize/', views.dropbox_oauth, name='dropbox_oauth'),
    path('authorized/', views.dropbox_authorized, name='dropbox_authorized'),
    # path('search-files/', views.search_files, name='search_files'),
    path('dropbox-folders/', views.dropbox_folders, name='dropbox_folders'),
    path('upload-file/', views.upload_file, name='upload_file'),
    path('success_upload/', views.success_upload, name='success_upload'),
    path('dropbox-folders/<path:folder_path>/', views.folder_files, name='folder_files'),
    path('download-file/<path:file_path>/', views.download_file, name='download_file'),
    path('remove-folder/<path:folder_path>/', views.remove_folder, name='remove_folder'),
    path('remove-file/<path:file_path>/', views.remove_file, name='remove_file'),
    path('dropbox-folders-docs/<path:folder_path>/', views.folder_files_docs, name='folder_files_docs'),
    path('dropbox-folders-pics/<path:folder_path>/', views.folder_files_images, name='folder_files_images'),
    path('dropbox-folders-video/<path:folder_path>/', views.folder_files_video, name='folder_files_video'),
    path('dropbox-folders-audio/<path:folder_path>/', views.folder_files_audio, name='folder_files_audio'),
]

src/contactsapp/urls.py
from django.urls import path
from . import views
from .views import ContactSendEmail

app_name = 'contactsapp'

urlpatterns = [
    path('add_contact/', views.add_contact, name='add_contact'),
    path('edit_contact/<int:contact_id>', views.edit_contact, name='edit_contact'),
    path('delete_contact/<int:contact_id>', views.delete_contact, name='delete_contact'),
    path('search_contact/', views.search_contact, name='search_contact'),
    path('upcoming_birthdays/', views.upcoming_birthdays, name='upcoming_birthdays'),
    path('detail_contact/<int:contact_id>', views.detail_contact, name="detail_contact"),
    path('<int:id>/email/',  ContactSendEmail.as_view(), name='send_email')
]

src/newsapp/urls.py
from django.shortcuts import render

# Create your views here.
from django.urls import path
from . import views

app_name = 'newsapp'

urlpatterns = [
    path('read_news/<str:q>/', views.choice_topic, name="read_news"),
    path('detail_paragraph/<str:q>/', views.paragraph, name="detail_paragraph"),
    ]

src/notesapp/urls.py
from django.urls import path
from . import views

app_name = 'notesapp'

urlpatterns = [
    path('search_note/', views.search_note, name="search_note"),
    path('search_tag/', views.search_tag, name="search_tag"),
    path('add_tag/', views.add_tag, name="add_tag"),
    path('add_note/', views.add_note, name="add_note"),
    path('detail_note/<int:note_id>', views.detail_note, name="detail_note"),
    path('detail_tag/<int:tag_id>', views.detail_tag, name="detail_tag"),
    path('delete_note/<int:note_id>', views.delete_note, name="delete_note"),
    path('delete_tag/<int:tag_id>', views.delete_tag, name="delete_tag"),
    path('edit_note/<int:note_id>', views.edit_note, name="edit_note"),
]

src/personal_assistant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from usersapp.views import root

urlpatterns = [
    path('', root, name='root'),
    path('admin/', admin.site.urls),
    path('users/', include('usersapp.urls')),
    path('bot/', include('ai_chat_bot.urls')),
    path('contacts/', include('contactsapp.urls')),
    path('notes/', include('notesapp.urls')),
    path('news/', include('newsapp.urls')),
    path('cloud_storageapp/', include('cloud_storageapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/usersapp/urls.py
from .views import main, login_user, create_user_profile, logout_user, ResetPasswordView, terms, activate, success
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static


app_name = 'usersapp'

urlpatterns = [
    path('', main, name='main'),

    path('terms/', terms, name='terms'),
    path('login/', login_user, name='login_user'),
    path('signup/', create_user_profile, name='create_user_profile'),
    path('logout/', logout_user, name='logout_user'),
    path('success/', success, name='success'),
    path('reset-password/', ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='usersapp/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='usersapp/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='usersapp/password_reset_complete.html'),
         name='password_reset_complete'),
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
            activate, name='activate'),
]

urlpatterns += staticfiles_urlpatterns()


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/usersapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    ROLE_CHOICES = (
        ('admin', 'Admin'),
        ('user', 'User'),
        ('manager', 'Manager'),
        ('developer', 'Developer'),
        ('support', 'Support'),
    )

    role = models.CharField(max_length=120, choices=ROLE_CHOICES, default='user')
    telegram_id = models.CharField(max_length=120, blank=True)

    def __str__(self):
        return f' User - {self.username} has a role:  {self.role}'

src/usersapp/forms.py
from django import forms
from .models import CustomUser
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


class CustomUserRegisterForm(UserCreationForm):
    email = forms.EmailField(max_length=100,
                             required=True,
                             widget=forms.EmailInput(attrs={'class': 'form-control'}))

    username = forms.CharField(max_length=20,
                               required=True,
                               widget=forms.TextInput(attrs={'class': 'form-control'}))

    first_name = forms.CharField(max_length=100,
                                 required=False,
                                 widget=forms.TextInput(attrs={'class': 'form-control'}))

    last_name = forms.CharField(max_length=100,
                                required=False,
                                widget=forms.TextInput(attrs={'class': 'form-control'}))

    password1 = forms.CharField(max_length=16,
                                required=True,
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(max_length=16,
                                required=True,
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = CustomUser
        fields = ['email', 'username', 'first_name', 'last_name', 'password1', 'password2']


class LoginForm(AuthenticationForm):
    # email = forms.EmailField(max_length=100,
    #                          required=True,
    #                          widget=forms.EmailInput(attrs={'class': 'form-control'}))

    username = forms.CharField(max_length=20,
                               required=True,
                               widget=forms.TextInput(attrs={'class': 'form-control'}))

    password = forms.CharField(max_length=16,
                               required=True,
                               widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = CustomUser
        fields = ['username', 'password']

src/usersapp/views.py
from django.core.mail import EmailMessage

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from . import forms
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.contrib.sites.shortcuts import get_current_site

from .tokens import account_activation_token

from .models import CustomUser


def main(request):
    return render(request=request, template_name='usersapp/index.html', context={})


def root(request):
    return render(request=request, template_name='usersapp/index.html', context={})


def terms(request):
    return render(request=request, template_name='usersapp/terms.html', context={})


def create_user_profile(request):
    if request.user.is_authenticated:
        return redirect('usersapp:main')

    if request.method == 'POST':
        form = forms.CustomUserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            # user.save()
            form.save()
            current_site = get_current_site(request)
            mail_subject = 'Activation link has been sent to your email id'
            message = render_to_string('usersapp/acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            print(message)
            to_email = form.cleaned_data.get('email')
            print(to_email)
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            print("Email Sending .....")
            email.send()
            return redirect('usersapp:login_user')

        else:
            print("Form is not valid!!!!!!!!!!!")
            form = forms.CustomUserRegisterForm()
            return render(request, 'usersapp/signup.html', context={"form": form})
    print("Method GET !!!!!!!!")
    form = forms.CustomUserRegisterForm()
    return render(request, 'usersapp/signup.html', context={"form": form})


def activate(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = CustomUser.objects.get(pk=uid)
        print("Run Activate ............")
        print(user.pk)

    except(TypeError, ValueError, OverflowError):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        print("User Not NONE !!!!!!!!!")
        user.is_active = True
        user.save()
        return redirect('usersapp:login_user')

    else:
        print("User is NONE !!!!!!!!!!!!!!")
        return redirect('usersapp:create_user_profile')


def login_user(request):
    if request.user.is_authenticated:
        return redirect(to='usersapp:main')

    if request.method == 'POST':
        print('I\'m in POST')
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        print(user)
        if user is None:
            print('I\'m in POST but user is NONE ')
            messages.error(request, 'Username or password didn\'t match')
            return redirect(to='usersapp:login_user')

        login(request, user)
        print("You was Logged IN !!!!!!!!!!!!!!!")
        return redirect(to='usersapp:main')

    form = forms.LoginForm()
    return render(request, 'usersapp/login.html', context={"form": form})


@login_required
def logout_user(request):
    logout(request)
    return redirect(to='usersapp:login_user')


@login_required
def success(request):
    return render(request, 'usersapp/success.html')


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'usersapp/password_reset.html'
    email_template_name = 'usersapp/password_reset_email.html'
    html_email_template_name = 'usersapp/password_reset_email.html'
    success_url = reverse_lazy('usersapp:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'usersapp/password_reset_subject.txt'

src/usersapp/templates/usersapp/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'usersapp:activate' uid token %}
{% endautoescape %}

src/usersapp/templates/usersapp/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
          crossorigin="anonymous">
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'usersapp/css/style.css' %}">
    <title> Django Project! </title>
</head>
<body>
{% if user.is_authenticated %}
{% include 'usersapp/navbar.html' %}
{% endif %}
<section class="vh-100 bg-image"
         style="background-image: url('https://mdbcdn.b-cdn.net/img/Photos/new-templates/search-box/img4.webp');">
    <div class="mask d-flex align-items-center h-100 gradient-custom-3">
        {% block content %}
        {% endblock %}
    </div>
</section>
{% include 'usersapp/footer.html' %}
</body>
</html>

src/usersapp/templates/usersapp/footer.html
<style>
    .li-padding {
    padding: 30px;
    }
</style>

<footer class="py-3 my-4">
    <p class="text-center text-muted">Created by:</p>
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
        <li class="nav-item mb-1 li-padding"><a href="https://github.com/osandrey" class="nav-link px-2 text-muted">Andriy
            Osypenko</a></li>
        <li class="nav-item mb-1 li-padding"><a href="https://github.com/VadimTrubay" class="nav-link px-2 text-muted">Vadim
            Trubay</a></li>
        <li class="nav-item mb-1 li-padding"><a href="https://github.com/Balanin" class="nav-link px-2 text-muted">Volodymyr
            Balan</a></li>
        <li class="nav-item mb-1 li-padding"><a href="https://github.com/KarynaSam" class="nav-link px-2 text-muted">Samoylenko
            Karyna</a></li>
    </ul>
    <p class="text-center text-muted">© {% now "Y" %} Personal Assistant Django</p>
</footer>

src/usersapp/templates/usersapp/index.html
{% extends 'usersapp/base.html' %}
{% load static %}
{% block content %}

<div class="container">
    <div class="card">
        <div class="big-text">
            <p><span style="color: #8351f9;">GoIT Team-8</span></p>
            <p><span style="color: #8351f9;">Produced in Ukraine</span></p>
            <p><span style="color: #8351f9;">Massive congrats to everyone who has taken part in the Project!</span></p>
            <p><span
                    style="color: #8351f9;">Inspiring mentors, thank you for knowledge and guidance. Grateful always!</span>
            </p>
            <p><span style="color: #8351f9;"></span>Keep Love in your heart!</p>
            <div class="d-flex justify-content-center button-container"><a href="{% url 'usersapp:login_user' %}">
                <button type="submit" class="btn btn-success btn-block btn-lg gradient-custom-5 text-body">Login
                </button>
            </a>
            </div>
        </div>

    </div>
</div>
<style>
    .container {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        margin: 0;
    }

    .card {
        border: 1px solid #ccc;
        border-radius: 5px;
        padding: 20px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        max-width: 800px;
    }

    .big-text {
        font-size: 18px;
        line-height: 1.6;
        color: #8351f9;
    }

</style>

{% endblock %}

src/usersapp/templates/usersapp/login.html
{% extends 'usersapp/base.html' %}
{% load static %}
{% block content %}
<div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-6 col-lg-6 col-xl-5">
            <div class="card" style="border-radius: 15px;">
                <div class="card-body p-5">
                    <h2 class="text-uppercase text-center mb-3">Login to your account</h2>
                    {% if form.errors %}
                    <span class="alert alert-danger" role="alert">{{form.non_field_errors}}</span>
                    {% endif %}
                    <form method="post" action="{% url 'usersapp:login_user' %}">
                        {% csrf_token %}
                        <div class="form-outline mb-2">
                            <!--                                    <input type="email" id="form3Example3cg" class="form-control form-control-lg"/>-->
                            <label class="form-label">Your Username: {{ form.username }}</label>
                            <span>{{form.errors.username}}</span>
                        </div>
                        <div class="form-outline mb-2">
                            <!--                                    <input type="text" id="form3Example6cg" class="form-control form-control-lg"/>-->
                            <label class="form-label">Your Password: {{ form.password }}</label>
                            <span>{{form.errors.password}}</span>
                        </div>
                        <div class="d-flex justify-content-center button-container">
                            <button type="submit" class="btn btn-success btn-block btn-lg gradient-custom-5 text-body">
                                Submit
                            </button>
                            <button type="reset" class="btn btn-success btn-block btn-lg gradient-custom-5 text-body">
                                Reset
                            </button>
                        </div>
                        <div class="small text-center button-container">
                            <a href="{% url 'usersapp:password_reset' %}" class="text-center"><i>Forgot
                                Password?</i></a></div>
                        <div class="small text-center button-container"><a
                                href="{% url 'usersapp:create_user_profile' %}" class="text-center"><i>Don't have
                            account yet?</i></a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

src/usersapp/templates/usersapp/logout.html
{% extends "usersapp/base.html" %}

{% block content %}

<h1>Thank you for using our services.</h1>

{% endblock %}

src/usersapp/templates/usersapp/navbar.html
<style>

details[role=list] summary+ul li a:hover, li[role=list]>ul li a:hover {
    background-color: hsl(205deg 1.47% 73.36%);
}
</style>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <div class="navbar-brand">
            <a class="navbar-brand" href="{% url 'usersapp:main' %}">
                {% load static %}<img src="{% static 'usersapp/media/logo.png' %}" alt="logo" width="200" height="100"/>
            </a>
        </div>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
                aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <button
                class="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#navbarScroll"
                aria-controls="navbarScroll"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarScroll">
            <ul>
                <li role="list" dir="rtl">
                    <a href="{% url 'contactsapp:search_contact' %}" aria-haspopup="listbox" role="button">Contact</a>
                    <ul role="listbox">
                        <li><a href="{% url 'contactsapp:search_contact' %}">Search contact</a></li>
                        <li><a href="{% url 'contactsapp:add_contact' %}">Add contact</a></li>
                        <li><a href="{% url 'contactsapp:upcoming_birthdays' %}">Upcoming birthdays</a>
                        </li>
                    </ul>
                </li>
            </ul>
            <ul>
                <li role="list" dir="rtl">
                    <a href="{% url 'notesapp:search_tag' %}" aria-haspopup="listbox" role="button">Tag</a>
                    <ul role="listbox">
                        <li><a href="{% url 'notesapp:search_tag' %}">Search tag</a></li>
                        <li><a href="{% url 'notesapp:add_tag' %}">Add tag</a></li>
                    </ul>
                </li>
            </ul>
            <ul>
                <li role="list" dir="rtl">
                    <a href="{% url 'notesapp:search_note' %}" aria-haspopup="listbox" role="button">Note</a>
                    <ul role="listbox">
                        <li><a href="{% url 'notesapp:search_note' %}">Search note</a></li>
                        <li><a href="{% url 'notesapp:add_note' %}">Add note</a></li>

                    </ul>
                </li>
            </ul>
            <ul>
                <li role="list" dir="rtl">
                    <a href="{% url 'cloud_storageapp:dropbox_folders' %}" aria-haspopup="listbox"
                       role="button">File</a>
                    <ul role="listbox">
                        <li><a href="{% url 'cloud_storageapp:upload_file' %}">Load file</a></li>
                        <li><a href="{% url 'cloud_storageapp:dropbox_folders' %}">Download file</a></li>
                    </ul>
                </li>
            </ul>

            <ul>
                <li role="list" dir="rtl">
                    <a href="#" aria-haspopup="listbox" role="button">News</a>
                    <ul role="listbox">
                        <li><a href="{% url 'newsapp:read_news' q='war_in_ukraine' %}"
                               id="btn_war_ukraine">War in Ukraine</a></li>
                        <li><a href="{% url 'newsapp:read_news' q='business' %}" id="btn_business">Business</a></li>
                        <li><a href="{% url 'newsapp:read_news' q='since' %}" id="btn_since">Since</a>
                        </li>
                    </ul>
                </li>
            </ul>

            {% if user.is_authenticated %}
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a href="{% url 'usersapp:logout_user' %}?next={% url 'usersapp:login_user' %}"
                       class="btn btn-success btn-block btn-lg gradient-custom-5 text-body">Logout</a>
                </li>
            </ul>
            {% else %}
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a href="{% url 'usersapp:login_user' %}" type="button"
                       class="btn btn-success btn-block btn-lg gradient-custom-5 text-body">Login</a>
                </li>
                <li class="nav-item ms-auto">
                    <a href="{% url 'usersapp:create_user_profile' %}" type="button"
                       class="btn btn-success btn-block btn-lg gradient-custom-5 text-body">Sign Up</a>
                </li>
            </ul>
            {% endif %}


        </div>
    </div>
    <style>

        ul[role="listbox"] {
            background-color: #f0f0f0; /* Replace with the desired color */
            padding: 10px; /* Optional: Add padding to the list */
            border-radius: 5px; /* Optional: Add border-radius for rounded corners */
        }

        details[role=list] summary+ul, li[role=list]>ul {

        z-index: 99;
        position: absolute;
        top: auto;
        right: 0;
        left: 0;
        flex-direction: column;
        margin: 0;
        padding: 0;
        border: var(--border-width) solid #f8f9fa;
        border-radius: var(--border-radius);
        border-top-right-radius: 0;
        border-top-left-radius: 0;
        background-color: #f0f0f0;
        box-shadow: var(--card-box-shadow);
        color: var(--dropdown-color);
        white-space: nowrap;
    }

        ul[role="list"][dir="rtl"] {
            background-color: #ffffff;


        ul li a {
            font-size: 15px;
        }

        ul li a {
          background-color: #f0f0f0; /* Replace this with the desired color */
          padding: 5px 10px; /* Add some padding to make the background visible */
          border-radius: 5px; /* Add border-radius for rounded corners */
          text-decoration: none; /* Remove underline from links */
    }


        ul li a:hover {
            background-color: #ccc; /* Replace this with the desired hover color */
        }

        .small-button-spacing {
            margin-bottom: 10px;
        }


    </style>
</nav>

src/usersapp/templates/usersapp/password_reset_done.html
{% extends "usersapp/base.html" %}

{% block content %}

<div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-6 col-lg-6 col-xl-5">
            <div class="card" style="border-radius: 15px;">
                <div class="card-body p-5">
                    <h2 class="text-uppercase text-center mb-3">Password reset request sen</h2>
                    <p>We've emailed you with instructions on how to reset your password!</p>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

src/usersapp/templates/usersapp/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'usersapp:password_reset_confirm' uidb64=uid token=token %}">
        {{ protocol }}://{{ domain }}{% url 'usersapp:password_reset_confirm' uidb64=uid token=token %}
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

src/usersapp/templates/usersapp/signup.html
{% extends 'usersapp/base.html' %}
{% load static %}
{% block content %}

<div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-8 col-md-6 col-lg-4 col-xl-6">
            <div class="card" style="border-radius: 15px; height: 800px; overflow-y: auto;">
                <div class="card-body d-flex flex-column align-items-center">
                    <h3 class="text-uppercase text-center mb-2">Create an account</h3>

                    <form method="post" action="{% url 'usersapp:create_user_profile' %}">
                        {% csrf_token %}
                        <div class="form-outline d-flex justify-content-center mb-1">
                            <!--                                    <input type="email" id="form3Example3cg" class="form-control form-control-lg"/>-->
                            <label class="form-label">Your Email: {{ form.email }}</label>
                            <span>{{form.errors.email}}</span>
                        </div>
                        <div class="form-outline d-flex justify-content-center mb-1">
                            <!--                                    <input type="text" id="form3Example6cg" class="form-control form-control-lg"/>-->
                            <label class="form-label">Your Username: {{ form.username }}</label>
                            <span>{{form.errors.username}}</span>
                        </div>
                        <div class="form-outline d-flex justify-content-center mb-1">
                            <!--                                    <input type="text" id="form3Example1cg" class="form-control form-control-lg"/>-->
                            <label class="form-label">Your First Name: {{ form.first_name }}</label>
                            <span>{{form.errors.first_name}}</span>
                        </div>

                        <div class="form-outline d-flex justify-content-center mb-1">
                            <!--                                    <input type="text" id="form3Example2cg" class="form-control form-control-lg"/>-->
                            <label class="form-label">Your Last Name: {{ form.last_name }}</label>
                            <span>{{form.errors.last_name}}</span>
                        </div>

                        <div class="form-outline d-flex justify-content-center mb-1">
                            <!--                                    <input type="password" id="form3Example4cg" class="form-control form-control-lg"/>-->
                            <label class="form-label">Password: {{ form.password1 }}</label>
                            <span>{{form.errors.password1}}</span>
                        </div>

                        <div class="form-outline d-flex justify-content-center mb-1">
                            <!--                                    <input type="password" id="form3Example4cdg" class="form-control form-control-lg"/>-->
                            <label class="form-label">Repeat your password: {{ form.password2 }}</label>
                            <span>{{form.errors.password2}}</span>
                        </div>

                        <div class="form-check d-flex justify-content-center mb-2">
                            <input class="form-check-input me-2" type="checkbox" value="" id="form2Example3cg"/>
                            <label class="form-check-label" for="form2Example3cg">
                                I agree all statements in <a href="{% url 'usersapp:terms' %}" class="text-body"><u>Terms
                                of service</u></a>
                            </label>
                        </div>

                        <div class="d-flex justify-content-center">
                            <button class="btn btn-success btn-block btn-lg gradient-custom-4 text-body">
                                Register
                            </button>
                        </div>

                        <p class="text-center text-muted mt-3 mb-0">Have already an account?
                            <a href="{% url 'usersapp:login_user' %}"
                               class="fw-bold text-body"><u>Login
                                here</u></a></p>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}